# Generated by Django 3.1.3 on 2021-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210106_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('img_one', models.CharField(max_length=100, null=True)),
                ('img_two', models.CharField(max_length=100, null=True)),
                ('img_three', models.CharField(max_length=100, null=True)),
                ('img_four', models.CharField(max_length=100, null=True)),
                ('img_five', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('reduc', models.IntegerField(null=True)),
                ('new', models.BooleanField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
