# Generated by Django 3.1.3 on 2021-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210106_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
