# Generated by Django 3.1.3 on 2021-01-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210123_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField()),
                ('file', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
