# Generated by Django 3.1.3 on 2021-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210128_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
